// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE4LMUKyspTKEyr2i9ElgmeV5z8rA273c',
    appId: '1:529973334654:web:51220300a2464815c93e2f',
    messagingSenderId: '529973334654',
    projectId: 'sweatmark-v1',
    authDomain: 'sweatmark-v1.firebaseapp.com',
    storageBucket: 'sweatmark-v1.firebasestorage.app',
    measurementId: 'G-0QCSZCREZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyKYicV_bo5gMFxh6n9l_FIJlJyQxzFDI',
    appId: '1:529973334654:android:7a950675d97c6d25c93e2f',
    messagingSenderId: '529973334654',
    projectId: 'sweatmark-v1',
    storageBucket: 'sweatmark-v1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrz7FbtFxT0n7bCkC2tKtR513yNP6IvqM',
    appId: '1:529973334654:ios:2b35f10468755e6ac93e2f',
    messagingSenderId: '529973334654',
    projectId: 'sweatmark-v1',
    storageBucket: 'sweatmark-v1.firebasestorage.app',
    iosBundleId: 'com.tt.sweatmark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrz7FbtFxT0n7bCkC2tKtR513yNP6IvqM',
    appId: '1:529973334654:ios:5724b0c2ce19c0dfc93e2f',
    messagingSenderId: '529973334654',
    projectId: 'sweatmark-v1',
    storageBucket: 'sweatmark-v1.firebasestorage.app',
    iosBundleId: 'com.example.sweatmark',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE4LMUKyspTKEyr2i9ElgmeV5z8rA273c',
    appId: '1:529973334654:web:51220300a2464815c93e2f',
    messagingSenderId: '529973334654',
    projectId: 'sweatmark-v1',
    authDomain: 'sweatmark-v1.firebaseapp.com',
    storageBucket: 'sweatmark-v1.firebasestorage.app',
    measurementId: 'G-0QCSZCREZN',
  );
}
